# Generated by Django 3.0.3 on 2020-03-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodata',
            name='endTime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='videodata',
            name='startTime',
            field=models.IntegerField(null=True),
        ),
    ]
