# Generated by Django 3.0.3 on 2020-03-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessor', '0002_auto_20200310_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodata',
            name='video_number',
            field=models.IntegerField(null=True),
        ),
    ]
