# Generated by Django 3.0.3 on 2020-03-10 01:03


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='clip_complete',
            field=models.BooleanField(default=False),
        ),
    ]
