# Generated by Django 3.0.3 on 2020-03-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoinfo',
            name='clip_complete',
            field=models.CharField(default='loading', max_length=50),
        ),
    ]
